name: Semantic release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run semantic release
      run: |
        npm install @semantic-release/commit-analyzer
        npm install @semantic-release/github
        npx semantic-release